#!/usr/bin/env bash

##########
# dotbot install script
# └─ https://github.com/anishathalye/dotbot/tree/v1.9.5/tools/git-submodule/install
##########
set -e

CONFIG="install.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
