#!/usr/bin/env bash

set -e

CONFIG="install.yaml"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTBOT_DIR="${BASEDIR}/dotbot"
DOTBOT_BIN="${DOTBOT_DIR}/bin/dotbot"

cd "${BASEDIR}"
git submodule update --init --recursive --quiet
"${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
