format = """
$username\
$hostname
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

# disable the blank line at the start of the prompt
add_newline = false

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[directory]
truncation_length = 10
truncation_symbol = "…/"
truncate_to_repo = false

[git_branch]
symbol = ''

[time]
disabled = false
format = '[$time]($style) '
style = '#63637B'
